"use strict";
let MyName = document.getElementById('name');
let des = document.getElementById('des');
let phone = document.getElementById('phone');
let email = document.getElementById('email');
let address = document.getElementById('address');
let pass1 = document.getElementById('pass1');
let deg1 = document.getElementById('deg1');
let uni1 = document.getElementById('uni1');
let pass2 = document.getElementById('pass2');
let deg2 = document.getElementById('deg2');
let uni2 = document.getElementById('uni2');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let lang1 = document.getElementById('lang1');
let lang2 = document.getElementById('lang2');
let lang3 = document.getElementById('lang3');
let startYear = document.getElementById('startYear');
let endYear = document.getElementById('endYear');
let company = document.getElementById('company');
let cmplocation = document.getElementById('cmplocation');
let jobTitle = document.getElementById('jobTitle');
let ach1 = document.getElementById('ach1');
let ach2 = document.getElementById('ach2');
let ach3 = document.getElementById('ach3');
let picture = document.getElementById('pic');
let submit = document.getElementById('submit');
let resumeForm = document.getElementById('resumeForm');
resumeForm?.addEventListener('submit', (e) => {
    e.preventDefault();
    localStorage.setItem("name", MyName.value);
    localStorage.setItem("des", des.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("address", address.value);
    localStorage.setItem("pass1", pass1.value);
    localStorage.setItem("deg1", deg1.value);
    localStorage.setItem("uni1", uni1.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("deg2", deg2.value);
    localStorage.setItem("uni2", uni2.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("lang1", lang1.value);
    localStorage.setItem("lang2", lang2.value);
    localStorage.setItem("lang3", lang3.value);
    localStorage.setItem("startYear", startYear.value);
    localStorage.setItem("endYear", endYear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("cmplocation", cmplocation.value);
    localStorage.setItem("jobTitle", jobTitle.value);
    localStorage.setItem("ach1", ach1.value);
    localStorage.setItem("ach2", ach2.value);
    localStorage.setItem("ach3", ach3.value);
    if (picture.files && picture.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let file = reader.result;
            localStorage.setItem("pic", file);
        });
        reader.readAsDataURL(picture.files[0]);
    }
    window.location.href = "./resume/index.html";
});
